[package]
name = "webg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
 

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.11.3"
log = "0.4.21"
wgpu = { version = "0.20.0", features = ["webgl"] }
pollster = "0.3.0"
